- .gitmodules
- README.md
- setup_bsc_relayer.sh
- setup_oracle_relayer.sh
Fixed small issues in scripts and improve submodule
> improve scripts & readme

- create_bls_key.exp
- setup_bc_node.sh
- setup_bsc_node.sh
1. flag `bls-wallet` should be provided, in couple with `side-vote-addr`  ,introduced by BEP255
2. update genesis contract to the latest version
> adapt for BEP255

- config.toml
- helm/bsc/templates/statefulset.yaml
- setup_bsc_node.sh
after big merge in bsc, some config and flags changed
this PR is to adapt for the changes
by the way, the script still can work with bsc before big merge, for example the master branch
> adapt for big merge

- setup_bsc_relayer.sh
- setup_oracle_relayer.sh
1. update genesis submodule to the latest of master branch
2. in native deploy mode, there may be more than one IP start with `192.168`
for now, the script will go wrong, just use the first one to fix it.
> use the latest genesis and the first IP start with '192.168'

- setup_bsc_node.sh
auto npm install and reset genesis
> auto npm install and reset genesis

- README.md
- setup_bsc_node.sh
This pr is to update the deploy script for the latest bsc & bsc-genesis-contracts version
> update for BC-fusion

- README.md
- setup_bsc_fullnode.sh
- start_fullnode.sh
scripts: add new fullnode helper script;
It can help to test syncing:
1. full sync: 
```bash
./setup_bsc_fullnode.sh 0 full
```
2. snap sync: 
```bash
./setup_bsc_fullnode.sh 1 snap
```
> Setup fullnode

- .env
- start_cluster.sh
- start_fullnode.sh
scripts: add new override flags for testing;
> scripts: add new override flags for testing;

- README.md
- start_cluster.sh
- start_fullnode.sh
scripts: support fast node & prune ancient;
> scripts: support fast node & prune ancient;

- README.md
- monitor/dashboard/validator-monitor-1712916445176.json
- monitor/docker-compose.yml
- monitor/grafana/provisioning/datasources/prometheus.yaml
- monitor/prometheus/prometheus.yml
feat: add grafana dashboard for testing;
> feat: add grafana dashboard for testing;

- start_cluster.sh
allow to specify validator Index to stop or start
> allow to specify validator Index to stop or start

- bsc_fullnode.sh
latest, there are some changes in `bsc_cluster.sh` of main branch
so `bsc_fullnode.sh` should adapt for them.
> rework fullnode

- bsc_cluster.sh
- bsc_fullnode.sh
prague and pascal have been enabled on mainnet, so remove override.prague and override.pascal
> remove override.prague and override.pascal

- .env
- .gitmodules
set EnableSentryNode to false by default
> set EnableSentryNode to false by default

- bsc_cluster.sh
This PR fixes a minor issue, it syncs the remote bsc submodule before compiling the bsc.
* chore: fix use latest bsc client issue;
> chore: fix use latest bsc client issue;

- bsc_cluster.sh
- txblob/main.go
- txbot/main.go
This PR will support full node to forward  tx between validators.
* script: support fullnode tx broadcast;
> script: support fullnode tx broadcast;

- README.md
- bsc_cluster.sh
- bsc_fullnode.sh
- config.toml
chore: improve robust & clean code, for brief:
1. change dir structure: .local/bsc --> .local
2. fix `prepare_bsc_client`, dir `${workspace}/bsc` must exist now
more details to see comments
> chore: improve robust & clean code

- README.md
- bsc_cluster.sh
> chore: don't force kill when stop

- bsc_cluster.sh
> chore: fix kill action

- config.toml
This PR will update changes in `config.toml`.
Add new config for sentry node.
```toml
[Node.P2P]
ProxyedValidatorAddresses = []
```
* config: update changes;
> config: update changes;

- bsc_cluster.sh
This PR will support exporting the proxyed validator address.
It will add config in sentry node.
```toml
[Node.P2P]
ProxyedValidatorAddresses = ["0xbcdd0d2cda5f6423e57b6a4dcd75decbe31aecf0"]
```
* script: support export proxyed validator address;
> script: support export proxyed validator address;

- bsc_cluster.sh
- qa-env-resource/bsc.service
- qa-env-resource/chaind.sh
- qa-env-resource/config.toml
This PR will support remote update config, and update config changes;
Reset remote config.
```bash
bash -x ./bsc_cluster.sh remote_reset_config
```
* script: support remote update config;
* script: update config changes;
> script: support remote update config;

- bsc_cluster.sh
- bsc_fullnode.sh
> support Fermi hardfork

- bsc_cluster.sh
> remove multidatabase flag
